apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: spring-tests-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer