version: '3.1'

services:


  user_db:
    image: postgres:10
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users

