name: Feature Close
on:
  pull_request:
    types: [closed]

jobs:
  clean-env:
    runs-on: [ self-hosted, decathlon ]
    steps:
      - name: clean
        uses: docker://centos
        if: ${{ always() }}
        continue-on-error: true
        with:
          args: "/bin/rm /github/workspace -rf"

      - uses: actions/checkout@v3

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3
        with:
          repository: dktunited/member-actions
          ref: v1
          token: ${{ secrets.DKTUNITED_TOKEN }}
          path: .github/member-actions

      - name: Setup variables
        uses: ./.github/member-actions/github-action-member-setup-env
        with:
          kube_config_data: ${{ secrets.MEMBER_KUBE_CONFIG_EPH_DATA }}

      - name: Clean ephemeral env
        run: |
          kubectl delete -n ${{env.ghrepo}}-${{ github.event.pull_request.number }} --force --grace-period 0 || true
          kubectl delete ns ${{env.ghrepo}}-${{ github.event.pull_request.number }} || true

      - name: Comment with URL
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const output = `Your environment has been cleaned. \n See you !  `;
            github.rest.issues.createComment({
                issue_number: "${{ github.event.pull_request.number }}",
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
            });
