name: Feature
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.draft == false
    steps:
      - name: clean
        uses: docker://centos
        if: ${{ always() }}
        continue-on-error: true
        with:
          args: "/bin/rm /github/workspace -rf"

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          settings-path: ${{ github.workspace }}
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: ./spring-boot3-crud-application
        run: mvn -q clean verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry Europe
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: ./spring-boot3-crud-application
          dockerfile: ./spring-boot3-crud-application/Dockerfile
          push: true
          build-args: |
            --no-cache
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-boot3-crud-application:${{ github.sha }}

      - name: Logout from Docker Hub
        run: |
          docker logout